### ISSUE TITLE
Finalize Stroke-CT

### ISSUE THREAD

**Issue by pintodossantos** [DRGagit/ak_befundung#17]
Das Template für Stroke muss noch an unsere Design-Vorgaben angepasst werden... @janpreuss vielleicht kannst du da von den Templates, die du bisher gemacht hast bisschen abschauen? Da sind teilweise `name` und `id` tags nicht ganz optimal, außerdem müsste man das in die Tabellen-Struktur packen, die wir gewohnt sind, würde ich sagen...
Und irgendwie funktionieren die Checkboxen auch nicht richtig... Gibt es Templates in denen wir schon Checkboxen haben?

@johann-martin 's aktuelle Version ist `CCT nativ Stroke.html`
habe schonmal angefangen aufzuräumen, bisherigen Stand kannst du unter `CCT nativ Stroke_pinto.html` finden...

**Comment by pintodossantos** [comment]
Ist das Stroke nativ Ding dann jetzt schon final fertig, @johann-martin?
Und wieviel Aufwand sind die Angio- und Perfusionstemplates, @janpreuss?

Bzw: ist es sinnvoll, dass das eigene Templates sind, @johann-martin? Oder würde es reichen, wenn man das quasi als Module hätte, die dann im Zweifel das Stroke-nativ-Template ergänzen?

**Comment by johann-martin** [comment]
Das revidierte Template sieht gut aus und ist vollständig.

**Comment by johann-martin** [comment]
Wegen Angio und Perfusion: Im Prinzip sind die als Module sinnvoll. Soweit ich das verstanden habe, ist der modulare Aufbau ohne JS nicht möglich und die müssen als eigentständige Templates erstellt werden?

**Comment by johann-martin** [comment]
sorry, falscher button

**Comment by pintodossantos** [comment]
> Das revidierte Template sieht gut aus und ist vollständig.

Ok, perfekt! Dann würde ich das abschließen und der DRG Bescheid geben.

> Wegen Angio und Perfusion: Im Prinzip sind die als Module sinnvoll. Soweit ich das verstanden habe, ist der modulare Aufbau ohne JS nicht möglich und die müssen als eigentständige Templates erstellt werden?

das stimmt... @janpreuss ist es viel Aufwand auf der Basis des nativ-Templates diese beiden Abwandlungen auch noch fertig zu machen? Danke!!

**Comment by janpreuss** [comment]
Das ist, denke ich, nicht so aufwändig. Die Templates sind ja schon weitgehend fertig. Wäre bis kommenden Montag noch ok?

**Comment by pintodossantos** [comment]
Von meiner Seite auf jeden Fall, vermutlich auch übernächste Woche noch ok... :) Danke!!

**Comment by johann-martin** [comment]
Reicht sicherlich - auch übernächste Woche ... ;-)


Am 28.04.21 um 17:07 schrieb Daniel Pinto dos Santos:

**Comment by pintodossantos** [comment]
> Bezüglich Angiographie: Ich hoffe die je nach Gefäß teilweise unterschiedlichen Auswahlmöglichkeiten für den Stenosegrad sind gut durchdacht. Für mich als noch unvollständig ausgebildeten Mediziner erschließt sich der Sinn dahinter nicht von selbst.

@johann-martin: kannst du das einmal checken? Danke!!

**Comment by johann-martin** [comment]
N'Abend zusammen,
habe die Angio- und Perfusionstemplates angeschaut - passt so.
Die unterschiedlichen Auswahlmöglichkeiten ergeben sich aus dem speziellen Gefäß(-abschnitt), bei dem unterschiedilche Pathologien in Betracht kommen oder nicht vorkommen. 
Z.B. Adaption der NASCET-Kriterien gilt nur für ACI extrakraniell, nicht für intrakraniell und auch für die hintere Zirkulation. Oder Dissektionen intrakraniell, z.B. der Media, gibt es de facto nur iathrogen.
Liebe Grüße

**Comment by janpreuss** [comment]
Wunderbar, dann wäre damit alles in Sachen Stroke erstmal fertig?

**Comment by johann-martin** [comment]
Jawoll

07.05.2021 09:51:57 janpreuss ***@***.***>:
