### ISSUE TITLE
Template Urolithiasis fertig machen

### ISSUE THREAD

**Issue by pintodossantos** [DRGagit/ak_befundung#19]
Hi,

die Kollegen aus Freiburg haben ein Template zur Urolithiasis ausgearbeitet, das nun auch von der AG Uroradiologie freigegeben wurde...

Ansprechpartner waren:

- elmar.kotter@uniklinik-freiburg.de
- jakob.neubauer@uniklinik-freiburg.de
- Lars.Schimmoeller@med.uni-duesseldorf.de (AG Uro)

Word-Datei packe ich gleich dann mal in das Repo.

@janpreuss das wäre ja vielleicht einfach und schnell umzusetzen. Wann immer es die Zeit dir erlaubt, kannst du da gerne loslegen. Vielleicht am besten einen ersten Aufschlag machen und dann gucken wir uns das gemeinsam an?

**Comment by janpreuss** [comment]
Entwurf Urolithiasis ist fertig: [https://github.com/DRGagit/ak_befundung/blob/master/templates_development_html/uro/ct_urolithiasis.html]. Die Templateautoren hatten sich gewünscht, dass der Block "Urolithiasis" für jedes Konkrement einzeln ausgefüllt wird. Leider bietet das Templateformat nicht die Möglichkeit einen Abschnitt nach Bedarf zu vervielfältigen und mehrfach auszufüllen, jedenfalls nicht ohne JavaScript. Da das ein Feature wäre, was öfters nützlich sein könnte, könnte man aber vielleicht mal erwägen das zu implementieren. Bis dahin ist ein Feld "Weitere Konkremente" hoffentlich ein ausreichender Behelf.
Eine weitere Frage wäre noch, ob man den Abschnitt "Beurteilung" noch in einzelne Items aufteilt oder es besser bei einem Freitextfeld belässt.

**Comment by pintodossantos** [comment]
Danke @janpreuss! Ich melde das einmal der AG Uro zurück und dann sehen wir was die denken! Ansonsten sieht das Template schon top aus!

**Comment by janpreuss** [comment]
Neue Änderungen sind eingepflegt mit einem Vorschlag für eine "Anleitung" als &lt;mark&gt;. Ist natürlich nicht wirklich schön so.
Würde es sich lohnen, doch nochmal über eine Javascript-Lösung nachzudenken, die das zumindest in einigen Editoren vereinfacht und "abwärtskompatibel" zu anderen Editoren ist? Ich könnte mir einen Entwurf überlegen.
