### ISSUE TITLE
MRT Rektum-Ca, mr_rectalca_N: <=3 statt <3?

### ISSUE THREAD

**Issue by tompelli** [DRGagit/ak_befundung#27]
Sollte es in diesem Template nicht heißen:

N+ (suspekte Lymphknoten mesorektal &le;3)

anstatt

N+ (suspekte Lymphknoten mesorektal &lt;3)

**Comment by tompelli** [comment]
Ich habe stattdessen einen Pull-Request angelegt, daher schließe ich dieses Issue.

**Comment by pintodossantos** [comment]
Stimmt, gute Idee! Danke für den PR. :)
