### ISSUE TITLE
SR Endoprotetik Hüfte in HTML umsetzen

### ISSUE THREAD

**Issue by pintodossantos** [DRGagit/ak_befundung#4]
Mail Braunschweig -> Völker

> Lieber Herr Völker,
>  
> hier nochmals für Ihren effektiven Zugriff die aktuelle und mit Herrn Janka abgestimmte Pilotversion zur strukt. Befundung des Hüftgelenkes zur Endoprothtetik.
>  
> Sobald Ihrerseits die Grundsatzentscheidung steht, mit wem ein Prototyp eines templates erstellt werden kann, schlage ich einen Termin vor (kann telco sein) indem wir mit den Umsetzern die einzelnen Punkte hinsichtlich ihrer it-technischen Hierarchisierung durchgehen.
>  
> Es wird z.B. it-technisch entscheidend sein darzustellen, dass methodische Angaben als Begleitinformation, jedoch die Befundkriterien als Kerninformation angeboten werden müssen. Zudem müssen die 4 kellgren-Stadien in der Moidifikation nach Braunschweig et al. Aufgenommen werden.
> Hierzu ist im Novemberheft des Radiologen eine entsprechende Modifikation von mir publiziert (Co-Autoren: Regier, Weber). Mit Herrn Weber werde ich noch im Altjahr eine Promotionsbetreuung beginnen (der 1. Termin ist am 13.12.2019) , die die modifizierte Klassifikation hinsichtlich der Inter-Observer-Stabilität bewertet. Ich denke, diese Ergebnisse liegen im Sommer vor und können dann als Sicherstellung benutzt werden. Prospektiv soll eine multicentrische Studie folgen (Herr Janka und Herr Weber haben bereits zugesagt), in der wir den interdisziplinären Nutzen des Konzeptes der „binären Kriterien“ (hier am Beispiel der modifizierten Kellgren-Klassifikation – z.B. positiver Vorhersagewert von Kellgren (Röntgen) und Vallotton (MR-)-Kriterien) ermitteln wollen.
>  
> Damit hätten wir excellentes Ausgangsmaterial für alle
>         weiteren großen Gelenke und deren „strukt. Befundung“ (Initiative der „Jungen Radiologen“) und
>         evtl. für spätere Anwendungen in der Initiative der „AI“.
>  
> Ich werde dies am kommenden Montag so vorstellen und bitte Sich, dies entsprechend mitzutragen.
>  
>  
> Herzlichen Dank
> Beste Grüße
> Ihr
> RB
>  
> PS: Bitte berücksichtigen Sie diesen Vorschlagspunkt in der Tagesordnung – Danke!

**Comment by AMB-Git-Hub** [comment]
Hi, also in der AG MSK wurde besprochen dieses Template unverändert weiter umzusetzen. Warum wurde es on hold gesetzt? @pintodossantos Das kann gerne wieder in die Bearbeitung, wir würden in unserer Road Map dann diese und Knochentumoren als MSK Themen den MR Befunden vorziehen.

**Comment by pintodossantos** [comment]
Ist eigentlich nur "on hold" weil sich Jan aktuell erstmal um die Herz-Templates (#13) kümmern soll, danach geht es dann mit den MSK-Sachen weiter. :)

**Comment by pintodossantos** [comment]
@AMB-Git-Hub ich denke das folgende sind Fragen, die du am besten beantworten kannst:

> Moin geschätzte Auftraggeber,
> 
> der erste Entwurf für das Hüftendoprothetik-Template ist fertig: templates_development_html/msk/cr_hueftendoprothetik.html
> Ich hätte noch zwei offene inhaltliche Fragen:
> 1. In der Vorlage steht, die Kriterien sollten dreistufig (diskret/mittelgradig/ausgeprägt) klassifiziert werden, die Option "diskret" bzw "geringgradig" wurde aber bei einigen Feldern weggelassen. Ist das so beabsichtigt oder sollte man es ändern?
> 2. Es wird in der Vorlage mehrfach Bezug auf den Kellgren-Score genommen. Soll man dafür noch ein eigenes Feld einfügen, oder genügen die gegebenen Optionen + Freitextfelder?
> 
> Beste Grüße,
> @janpreuss

**Comment by pintodossantos** [comment]
Vielleicht interessant: https://pubmed.ncbi.nlm.nih.gov/34861708/

**Comment by janpreuss** [comment]
Hab's mal vorläufig korrigiert, folgende Anmerkungen dazu:

Was linke/rechte Hüfte betrifft: Es wird doch nur eine Hüftendoprothese auf einmal implantiert. Ich nahm an, die betroffene Hüfte soll befundet werden? Oder ist es üblich, immer beide Hüftgelenke zu befunden? In dem Fall könnte man natürlich die Felder duplizieren.

Die gelben Texte sind <mark>s, sie werden nur dem Befunder angezeigt, erscheinen aber nicht im fertigen Befundbericht (laut Guidelines). Hab's mal vorläufig dringelassen, kann man aber natürlich auch ganz löschen.

Zur Gelenkstellung: Sollen demnach die sieben Optionen regelrecht, gering inkongruent (varisch), mittelgradig inkongruent (varisch), ausgeprägt inkongruent (varisch), gering inkongruent (valgisch), mittelgradig inkongruent (valgisch), ausgeprägt inkongruent (valgisch) auswählbar sein?

Alles Weitere passt nun hoffentlich.
